# Generated by Django 4.2.6 on 2023-12-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('shop', '0003_seller_slug'), ('shop', '0004_remove_seller_slug')]

    dependencies = [
        ('shop', '0002_brand_favorite'),
    ]

    operations = [
    ]
